### ISSUE TITLE
src/pl_cuda.c undeclared `PG_WAIT_EXTENSION`

### ISSUE THREAD

**Issue by japinli** [heterodb/pg-strom#401]
When I compile pg-strom v2 on Ubuntu 18.04 with postgresql-9.6.11, cuda-10.0, I get an error:

```
src/pl_cuda.c:1092:11: error: ‘PG_WAIT_EXTENSION’ undeclared (first use in this function); did you mean ‘OCLASS_EXTENSION’?
           PG_WAIT_EXTENSION);
           ^~~~~~~~~~~~~~~~~
           OCLASS_EXTENSION
src/pl_cuda.c:1092:11: note: each undeclared identifier is reported only once for each function it appears in
src/pl_cuda.c:1085:8: error: too many arguments to function ‘WaitLatchOrSocket’
   ev = WaitLatchOrSocket(MyLatch,
        ^~~~~~~~~~~~~~~~~
In file included from /home/japin/xxpg9.6.11/include/postgresql/server/storage/proc.h:19:0,
                 from /home/japin/xxpg9.6.11/include/postgresql/server/storage/shm_mq.h:18,
                 from /home/japin/xxpg9.6.11/include/postgresql/server/access/parallel.h:20,
                 from /home/japin/xxpg9.6.11/include/postgresql/server/executor/nodeCustom.h:15,
                 from src/pg_strom.h:65,
                 from src/pl_cuda.c:18:
/home/japin/xxpg9.6.11/include/postgresql/server/storage/latch.h:163:12: note: declared here
 extern int WaitLatchOrSocket(volatile Latch *latch, int wakeEvents,
            ^~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'src/pl_cuda.o' failed
make: *** [src/pl_cuda.o] Error 1
```
Which version exactly do you try to build?

**Comment by japinli** [comment]
I tried to use PostgreSQL 10.6, and everything works fine. Is pg-strom v2 do not support postgresql 9.6.x ?

**Comment by kaigai** [comment]
Sorry, I didn't check build on PG9.6.
70888549bb8fedcfc451d4fa2f5b9866b9153593 fixes the build error.
