### ISSUE TITLE
nvme install error

### ISSUE THREAD

**Issue by ujangja** [heterodb/pg-strom#479]
env:

centos 7.9 x86-64
cuda 11.1
NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1

rpm -ivh nvme_strom-2.3-1.el7.x86_64.rpm

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j160 KERNELRELEASE=3.10.0-1160.el7.x86_64 -C . KERNEL_VER=3.10.0-1160.el7.x86_64 BUILD_BY_DKMS=1 modules...
cleaning build area...

DKMS: build completed.

nvme_strom.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-1160.el7.x86_64/extra/
Adding any weak-modules

depmod...
Job for systemd-modules-load.service failed because the control process exited with error code. See "systemctl status systemd-modules-load.service" and "journalctl -xe" for details.

Backing up initramfs-3.10.0-1160.el7.x86_64.img to /boot/initramfs-3.10.0-1160.el7.x86_64.img.old-dkms
Making new initramfs-3.10.0-1160.el7.x86_64.img
(If next boot fails, revert to initramfs-3.10.0-1160.el7.x86_64.img.old-dkms image)

dracut.................

DKMS: install completed.
Error! The module/version combo: rdmax-2.3
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/rdmax/2.3/source ->
                 /usr/src/rdmax-2.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j160 KERNELRELEASE=3.10.0-1160.el7.x86_64 -C . KERNEL_VER=3.10.0-1160.el7.x86_64 NVME_STROM_VERSION=2.3 modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.10.0-1160.el7.x86_64 (x86_64)
Consult /var/lib/dkms/rdmax/2.3/build/make.log for more information.
notice: rdmax -v 2.3 might be manually installed.

cat /var/lib/dkms/rdmax/2.3/build/make.log
DKMS make.log for rdmax-2.3 for kernel 3.10.0-1160.el7.x86_64 (x86_64)
Fri Nov 27 14:31:44 WIB 2020
make: Entering directory `/var/lib/dkms/rdmax/2.3/build'
make -C /lib/modules/3.10.0-1160.el7.x86_64/build M=/var/lib/dkms/rdmax/2.3/build
make[1]: Entering directory `/usr/src/kernels/3.10.0-1160.6.1.el7.x86_64'
  LD      /var/lib/dkms/rdmax/2.3/build/built-in.o
  CC [M]  /var/lib/dkms/rdmax/2.3/build/nvme-rdma.o
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:55:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘nvme_rdma_init_module’
 nvme_rdma_init_module(void)
 ^
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:59:1: warning: data definition has no type or storage class [enabled by default]
 module_init(nvme_rdma_init_module);
 ^
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:59:1: warning: type defaults to ‘int’ in declaration of ‘module_init’ [-Wimplicit-int]
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:59:1: warning: parameter names (without types) in function declaration [enabled by default]
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:61:16: error: expected declaration specifiers or ‘...’ before string constant
 MODULE_LICENSE("GPL v2");
                ^
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:63:20: error: expected declaration specifiers or ‘...’ before string constant
 MODULE_DESCRIPTION("Enhanced nvme-rdma for SSD-to-GPU Direct SQL");
                    ^
<command-line>:0:20: error: expected declaration specifiers or ‘...’ before string constant
/var/lib/dkms/rdmax/2.3/build/nvme-rdma.c:65:16: note: in expansion of macro ‘NVME_STROM_VERSION’
 MODULE_VERSION(NVME_STROM_VERSION);
                ^
make[2]: *** [/var/lib/dkms/rdmax/2.3/build/nvme-rdma.o] Error 1
make[1]: *** [_module_/var/lib/dkms/rdmax/2.3/build] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-1160.6.1.el7.x86_64'
make: *** [modules] Error 2
make: Leaving directory `/var/lib/dkms/rdmax/2.3/build'

**Comment by kaigai** [comment]
Does `nvme_strom-2.4-3.el7.x86_64.rpm` work for you?

It contains RHEL7.9 kernel (3.10.0-1160) support.

**Comment by ujangja** [comment]
Error loading the module

Nov 28 05:18:12 localhost kernel: nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  455.32.00  Wed Oct 14 22:38:43 UTC 2020
Nov 28 05:18:12 localhost kernel: nvidia_drm: disagrees about version of symbol nvKmsKapiGetFunctionsTable
Nov 28 05:18:12 localhost kernel: nvidia_drm: Unknown symbol nvKmsKapiGetFunctionsTable (err -22)
Nov 28 05:18:12 localhost kernel: nvidia_drm: disagrees about version of symbol nvKmsKapiGetFunctionsTable
Nov 28 05:18:12 localhost kernel: nvidia_drm: Unknown symbol nvKmsKapiGetFunctionsTable (err -22)
Nov 28 05:18:20 localhost systemd: Starting Load Kernel Modules...
Nov 28 05:18:20 localhost kernel: nvme-strom: kernel version (3.10.0-1160.el7.x86_64) is mismatch for this build (dkms: 3.10.0-1160.6.1.el7.x86_64)
Nov 28 05:18:20 localhost systemd-modules-load: Failed to insert 'nvme_strom': Invalid argument
Nov 28 05:18:20 localhost systemd: systemd-modules-load.service: main process exited, code=exited, status=1/FAILURE
Nov 28 05:18:20 localhost systemd: Failed to start Load Kernel Modules.

**Comment by kaigai** [comment]
It looks to me the nvme_strom module was built for 3.10.0-1160.6.1.el7.x86_64 kernel, but running kernel is 3.10.0-1160.el7.x86_64.
Could you restart the system with the kernel 3.10.0-1160.6.1.el7.x86_64?

It often happens if we updated the Linux kernel, but not reboot yet.

**Comment by ujangja** [comment]
I've updated the kernel and it is  3.10.0-1160.6.1.el7.x86_64 now; but there is still error:

[root@localhost ~]# rpm -ivh nvme_strom-2.4-3.el7.x86_64.rpm
warning: nvme_strom-2.4-3.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4eb31320: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:nvme_strom-2.4-3.el7             ################################# [100%]
Error! The module/version combo: nvme_strom-2.4
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/nvme_strom/2.4/source ->
                 /usr/src/nvme_strom-2.4

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j160 KERNELRELEASE=3.10.0-1160.6.1.el7.x86_64 -C . KERNEL_VER=3.10.0-1160.6.1.el7.x86_64 BUILD_BY_DKMS=1 modules...
cleaning build area...

DKMS: build completed.

nvme_strom.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-1160.6.1.el7.x86_64/extra/
Adding any weak-modules
depmod: ERROR: fstatat(8, nvme_strom.ko.xz): No such file or directory

depmod....

Backing up initramfs-3.10.0-1160.6.1.el7.x86_64.img to /boot/initramfs-3.10.0-1160.6.1.el7.x86_64.img.old-dkms
Making new initramfs-3.10.0-1160.6.1.el7.x86_64.img
(If next boot fails, revert to initramfs-3.10.0-1160.6.1.el7.x86_64.img.old-dkms image)
dracut..................

DKMS: install completed.
Error! The module/version combo: rdmax-2.4
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/rdmax/2.4/source ->
                 /usr/src/rdmax-2.4

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j160 KERNELRELEASE=3.10.0-1160.6.1.el7.x86_64 -C . KERNEL_VER=3.10.0-1160.6.1.el7.x86_64 NVME_STROM_VERSION=2.4 modules...
cleaning build area...

DKMS: build completed.

nvme-rdma.ko.xz:
Running module version sanity check.
 - Original module
   - Found /lib/modules/3.10.0-1160.6.1.el7.x86_64/extra/nvme-rdma.ko.xz
   - Storing in /var/lib/dkms/rdmax/original_module/3.10.0-1160.6.1.el7.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/3.10.0-1160.6.1.el7.x86_64/extra/
Adding any weak-modules
depmod: ERROR: fstatat(8, nvme_strom.ko.xz): No such file or directory

depmod....

Backing up initramfs-3.10.0-1160.6.1.el7.x86_64.img to /boot/initramfs-3.10.0-1160.6.1.el7.x86_64.img.old-dkms
Making new initramfs-3.10.0-1160.6.1.el7.x86_64.img
(If next boot fails, revert to initramfs-3.10.0-1160.6.1.el7.x86_64.img.old-dkms image)
dracut..................

DKMS: install completed.

[root@localhost ~]# reboot


but after reboot, the module can be loaded :

[root@localhost ~]# lsmod | grep nv
nvidia_drm             48711  0
nvidia_modeset       1212794  1 nvidia_drm
nvme_strom            102115  0
nvidia_uvm            966587  0
nvidia              27640019  5 nvidia_modeset,nvidia_uvm
drm_kms_helper        186531  2 mgag200,nvidia_drm
drm                   456166  5 ttm,drm_kms_helper,mgag200,nvidia_drm
libnvdimm             159524  1 nfit
nvme                   32382  0
nvme_core              63547  2 nvme


/var/log/messages : 

Nov 28 09:31:13 localhost kernel: nvme-strom: GPU-UUID: [GPU-6c52b9f7-adbb-adea-91da-8dee91458067] is not licensed
Nov 28 09:31:13 localhost kernel: nvme-strom: GPU-UUID: [GPU-413ff188-80fb-fa96-0cc5-b9549af9cc95] is not licensed
Nov 28 09:31:13 localhost kernel: nvme-strom: License Loaded { version: 2, serial_nr: HDB-TRIAL, issued_at: 2019-05-09, expired_at: 2019-06-08 }

**Comment by kaigai** [comment]
It looks to me nvme-strom.ko and nvme-rdma.ko were successfully built and installed.
But nvme-strom module raised an error due to the license expired.

Probably, `modinfo nvme_strom` and `modinfo nvme-rdma` shows proper module information. Right?
